apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
  name: { _service_name_ }
  labels:
    app.kubernetes.io/name: { _service_name_ }
    app.kubernetes.io/version: { _version_ }
    app.kubernetes.io/component: bpm
    app.kubernetes.io/part-of: riskengine
spec:
  replicas: 1
  image: { _image_ }
